>P1;omega
Structure: omega: 2:A : 100:A ::::
DADVISFEASR-GDLVVLDAIHDARFETEAGPGVYDIHSPRIPSEKEIEDRIYEILDKIDVKKVWINPDC
GLKTRGNDETWPSLEHLVAAAKAVRARLDK*
>P1;open
Structure: open: 2:A : 100:A ::::
DADVISFEASRGD-LVVLDAIHDARFETEAGPGVYDIHSPRIPSEKEIEDRIYEILDKIDVKKVWINPDC
GLKTRGNDETWPSLEHLVAAAKAVRARLDK*

